### ISSUE TITLE
[CHORE] HELLO NAPPED!

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_RDC_NAPPED#1]
## 📑 작업 사항 
프로젝트 초기 셋업 

## To-do
- [x] 앱 모듈 구성 
- [x] 사용할 종속성 추가하기 
- [x] 문서 작업 및 README 이미지 추가하기 
- [x] Firebase 등록하기 및 종속성 추가 

# #✔️ 기타사항
