### ISSUE TITLE
[FEATURE] 회사 리스트 DB 구축 및 가져오기 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_RDC_NAPPED#5]
## 📑 작업 사항 
병역 일터 엑셀 데이터 -> DB로 옮기기
data, domain module set up
공공 API, DB에서 데이터 가져오기 
데이터 UI에 매핑 

## To-do
- [x] 병역 일터 엑셀 데이터 -> DB로 옮기기
- [x] data, domain module set up
- [x] 공공 API, DB에서 데이터 가져오기 
- [x] 데이터 UI에 매핑 

# #✔️ 기타사항
