### ISSUE TITLE
[FEATURE] 게시판 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_RDC_NAPPED#7]
## 📑 작업 사항 
Firestore 팁 게시글 데이터 저장
Firestore 데이터 불러오기 및 Ui 매핑하기 

## To-do
- [x] 팁 게시글 데이터 저장 
- [x] Firestore 종속성 추가 및 불러오기
- [x] Ui 생성 및 매핑하기 

# #✔️ 기타사항
